# SPDX-FileCopyrightText: 2023 Dom Rodriguez (shymega) <shymega+mc-fly-away@shymega.org.uk>
#
# SPDX-License-Identifier: AGPL-3.0-only

---
name: CI - Nix tests

on:
  workflow_call:

jobs:
  run-tests:
    name: Nix CI tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@V27
      - run: nix profile install --accept-flake-config nixpkgs#devenv
      - run: devenv test
